# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: greet/greetpb/greet.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "greet.Greeting" do
    optional :first_name, :string, 1
    optional :last_name, :string, 2
  end
  add_message "greet.GreetRequest" do
    optional :greeting, :message, 1, "greet.Greeting"
  end
  add_message "greet.GreetResponse" do
    optional :result, :string, 1
  end
  add_message "greet.GreetManyTimesRequest" do
    optional :greeting, :message, 1, "greet.Greeting"
  end
  add_message "greet.GreetManyTimesResponse" do
    optional :result, :string, 1
  end
  add_message "greet.LongGreetRequest" do
    optional :greeting, :message, 1, "greet.Greeting"
  end
  add_message "greet.LongGreetResponse" do
    optional :result, :string, 1
  end
  add_message "greet.GreetEveryoneRequest" do
    optional :greeting, :message, 1, "greet.Greeting"
  end
  add_message "greet.GreetEveryoneResponse" do
    optional :result, :string, 1
  end
  add_message "greet.SquareRootRequest" do
    optional :number, :int32, 1
  end
  add_message "greet.SquareRootResponse" do
    optional :number_root, :double, 1
  end
  add_message "greet.GreetDeadlineRequest" do
    optional :greeting, :message, 1, "greet.Greeting"
  end
  add_message "greet.GreetDeadlineResponse" do
    optional :result, :string, 1
  end
end

module Greet
  Greeting = Google::Protobuf::DescriptorPool.generated_pool.lookup("greet.Greeting").msgclass
  GreetRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("greet.GreetRequest").msgclass
  GreetResponse = Google::Protobuf::DescriptorPool.generated_pool.lookup("greet.GreetResponse").msgclass
  GreetManyTimesRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("greet.GreetManyTimesRequest").msgclass
  GreetManyTimesResponse = Google::Protobuf::DescriptorPool.generated_pool.lookup("greet.GreetManyTimesResponse").msgclass
  LongGreetRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("greet.LongGreetRequest").msgclass
  LongGreetResponse = Google::Protobuf::DescriptorPool.generated_pool.lookup("greet.LongGreetResponse").msgclass
  GreetEveryoneRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("greet.GreetEveryoneRequest").msgclass
  GreetEveryoneResponse = Google::Protobuf::DescriptorPool.generated_pool.lookup("greet.GreetEveryoneResponse").msgclass
  SquareRootRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("greet.SquareRootRequest").msgclass
  SquareRootResponse = Google::Protobuf::DescriptorPool.generated_pool.lookup("greet.SquareRootResponse").msgclass
  GreetDeadlineRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("greet.GreetDeadlineRequest").msgclass
  GreetDeadlineResponse = Google::Protobuf::DescriptorPool.generated_pool.lookup("greet.GreetDeadlineResponse").msgclass
end
